### ISSUE TITLE
Use of \linethickness as a length variable

### ISSUE THREAD

**Issue by eleurent** [Naereen/phd-thesis#25]
In macrosText.sty, you define a command `\hr` which uses` \linethickness`.
But \linethickness seems to be a [command](http://www.emerson.emory.edu/services/latex/latex_50.html) rather than a variable, and expects an argument.
I get the following error:
```Illegal unit of measure (pt inserted). \hr```

Which I fixed by adding a definition
`\def \linethickness {0.4pt}`

**Comment by Naereen** [comment]
That's a great catch, thanks!
Where do I add this, where I define `\hr` ?
