### ISSUE TITLE
Includegraphics uses (missing) pdf rather than png?

### ISSUE THREAD

**Issue by eleurent** [Naereen/phd-thesis#26]
In many places, you include pdf files where only a png version exists instead, e.g.:
* \includegraphics[width=1.05\linewidth]{3.pdf}
* \includegraphics[width=1.05\linewidth]{3_hist.pdf}
* \includegraphics[width=1.10\linewidth]{16_different_algorithms__lognormregret_vs_arms__16pb__T5000.pdf}

I suspect that the pdf version (vector graphics) of these images have not been commited because of the .gitignore ?

**Comment by Naereen** [comment]
Very nice catch, indeed I was trapped by my aggressive `.gitignore`!

I checked the file that (sh/c)ould be added with
```bash
$ for i in $(agrep 'includegraphics.*\{.*\.pdf\}' **/*.tex | grep -o '\{.*\.pdf\}' | tr -d '\{\}' | sort | uniq); do j=$(basename $i); [ -f **/$j ] && echo git add -vf **/$j; done
```
and added them with a one-line command
```bash
$ for i in $(agrep 'includegraphics.*\{.*\.pdf\}' **/*.tex | grep -o '\{.*\.pdf\}' | tr -d '\{\}' | sort | uniq); do j=$(basename $i); [ -f **/$j ] && git add -vf **/$j; done
```
Thanks! (see d29c253)

**Comment by Naereen** [comment]
![](https://media.giphy.com/media/l2YWhOEwfSAnJNJEQ/giphy.gif)

![](https://media.giphy.com/media/3ornka9rAaKRA2Rkac/giphy.gif)

**Comment by eleurent** [comment]
Nice one-liner, but you missed the `\includepdf` calls such as `6-Back/Back.pdf`
