### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by iLPdev** [Naereen/phd-thesis#27]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] congratulatory message

* **What is the expected behavior?**
ABD

* **What is the current behavior?**
Dr. Lilian Besson

* **What is the motivation / use case for changing the behavior?**
![phd](https://user-images.githubusercontent.com/1428343/86823803-276c3980-c042-11ea-970e-819833843e60.jpg)

* **Please tell us about your environment:**
  
  - Degree: BA (1995), MA (1998), PhD (2008)
  - Major: Psychology
  - Specialization: Clinical

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

When I entered my mentor's research lab on the first day, the outgoing student informed that their doctoral experience had been that of being thrown into a dark cave and beaten with sticks by faculty for six years. He reported that after six years of isolation and abuse, they let you out into the light... and hand you a stick. If this was also your experience, please, put down your stick. ;)

**Comment by Naereen** [comment]
Thanks!
